services:
        db:
                image: postgres:latest
                restart: always
                environment:
                        POSTGRES_PASSWORD: parangaricutirrimirruaro
                        POSTGRES_USER: usuario
                volumes:
                        - db:/var/lib/postgresql/data
                ports:
                        - "5999:5432"
volumes:
        db:
