# Generated by Django 4.2.13 on 2024-07-03 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TOKEN', models.CharField(max_length=256)),
                ('UPTO', models.IntegerField(default='2024-07-03T19:55:05.085227')),
            ],
            options={
                'db_table': 'TM_TOKENS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('LOGIN', models.CharField(max_length=256)),
                ('PASS', models.CharField(max_length=256)),
                ('EMAIL', models.CharField(max_length=512)),
                ('TIMESTAMP_INS', models.DateTimeField(default=datetime.datetime(2024, 7, 3, 18, 55, 5, 85511))),
                ('TIMESTAMP_UPD', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'TM_USERS',
                'managed': True,
            },
        ),
    ]
