# Generated by Django 4.2.13 on 2024-07-03 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='UPTO',
            field=models.IntegerField(default='2024-07-03T19:58:48.215298'),
        ),
        migrations.AlterField(
            model_name='user',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 18, 58, 48, 215577)),
        ),
        migrations.AlterField(
            model_name='user',
            name='TIMESTAMP_UPD',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
