# Generated by Django 4.2.13 on 2024-07-03 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_token_upto_alter_user_timestamp_ins'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='IPADDR',
            field=models.CharField(default='127.0.0.1', max_length=16),
        ),
        migrations.AlterField(
            model_name='token',
            name='UPTO',
            field=models.IntegerField(default='2024-07-03T21:25:05.672882'),
        ),
        migrations.AlterField(
            model_name='user',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 20, 25, 5, 673186)),
        ),
    ]
