# Generated by Django 4.2.13 on 2024-07-11 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_token_ipaddr_alter_token_upto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='SECRET_KEY',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='UPTO',
            field=models.IntegerField(default='2024-07-11T12:29:10.298612'),
        ),
        migrations.AlterField(
            model_name='user',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 11, 29, 10, 298957)),
        ),
    ]
