# Generated by Django 4.2.13 on 2024-07-11 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_token_secret_key_alter_token_upto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ACTION', models.CharField(max_length=32)),
                ('PAYLOAD', models.CharField(max_length=4096)),
                ('RESPONSE', models.CharField(max_length=4096)),
                ('TIMESTAMP_INS', models.DateTimeField(default=datetime.datetime(2024, 7, 11, 12, 19, 28, 779124))),
            ],
            options={
                'db_table': 'TM_LOGS',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='token',
            name='UPTO',
            field=models.IntegerField(default='2024-07-11T13:19:28.778363'),
        ),
        migrations.AlterField(
            model_name='user',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 12, 19, 28, 778797)),
        ),
    ]
