# Generated by Django 4.2.13 on 2024-07-11 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_log_alter_token_upto_alter_user_timestamp_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 19, 27, 7, 559846)),
        ),
        migrations.AlterField(
            model_name='token',
            name='UPTO',
            field=models.IntegerField(default='2024-07-11T20:27:07.559215'),
        ),
        migrations.AlterField(
            model_name='user',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 19, 27, 7, 559543)),
        ),
    ]
