# Generated by Django 4.2.13 on 2024-07-11 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_alter_log_timestamp_ins_alter_token_upto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 19, 28, 34, 693231)),
        ),
        migrations.AddField(
            model_name='token',
            name='TIMESTAMP_UPD',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 19, 28, 34, 693876)),
        ),
        migrations.AlterField(
            model_name='token',
            name='UPTO',
            field=models.IntegerField(default='2024-07-11T20:28:34.693188'),
        ),
        migrations.AlterField(
            model_name='user',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 19, 28, 34, 693568)),
        ),
    ]
