# Generated by Django 4.2.13 on 2024-07-17 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_token_timestamp_ins_token_timestamp_upd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 12, 21, 17, 692789)),
        ),
        migrations.AlterField(
            model_name='token',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 12, 21, 17, 692055)),
        ),
        migrations.AlterField(
            model_name='token',
            name='UPTO',
            field=models.IntegerField(default='2024-07-17T13:21:17.691903'),
        ),
        migrations.AlterField(
            model_name='user',
            name='TIMESTAMP_INS',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 12, 21, 17, 692375)),
        ),
    ]
